const cities = [
    "Select One",
    "Istanbul",
    "Amsterdam",
    "Athens",
    "Barcelona",
    "Berlin",
    "Bratislava",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Copenhagen",
    "Dublin",
    "Gdansk",
    "Gothenburg",
    "Hamburg",
    "Helsinki",
    "Krakow",
    "Lisbon",
    "Ljubljana",
    "Lyon",
    "Madrid",
    "Milan",
    "Munich",
    "Naples",
    "Nice",
    "Nuremberg",
    "Oslo",
    "Paris",
    "Porto",
    "Prague",
    "Riga",
    "Rome",
    "Rotterdam",
    "Seville",
    "Sofia",
    "Stockholm",
    "Tallinn",
    "Turin",
    "Valencia",
    "Vienna",
    "Vilnius",
    "Warsaw",
    "Zagreb"
];

export default cities;
